name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.9.0

    - name: Publish .NET Project
      run: dotnet publish Core2D.Web/Core2D.Web.csproj -c Debug -o release --nologo

    - name: Change base-tag in index.html from / to Core2D.Web
      run: sed -i 's/<base href="\/" \/>/<base href="\/Core2D.Web\/" \/>/g' release/wwwroot/index.html

    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
